apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: mealie-deployment
  name: mealie-deployment
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-deployment
  template:
    metadata:
      labels:
        app: mealie-deployment
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v1.2.0
        name: mealie
        ports:
        - containerPort: 9000
