apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ouwais-deployment
  name: ouwais-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ouwais-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: ouwais-deployment
    spec:
      containers:
      - image: nginx:1.28.2
        name: nginx
        resources: {}
status: {}
