apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ouwais-deployment
  name: ouwais-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ouwais-deployment
  template:
    metadata:
      labels:
        app: ouwais-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
